# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Linux

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      wget "https://github.com/gohugoio/hugo/releases/download/v$(HUGO_RELEASE)/hugo_extended_$(HUGO_RELEASE)_Linux-64bit.deb"
      sudo dpkg -i hugo*.deb
      hugo version
      hugo

- task: GitHubPagesPublish@1
  inputs:
    docPath: 'public'
    githubusername: 'kuzhao'
    githubaccesstoken: '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'
    repositoryname: 'kuzhao.github.io'
    branchname: 'master'
    commitmessage: 'Automated Release $(Build.SourceVersion)'